### PR TITLE
feat: add prettier telescope previewer that displays open buffers

### PR DESCRIPTION
**Pull request by jedrzejboczar**
Example implementation of https://github.com/jedrzejboczar/possession.nvim/pull/43#issuecomment-1777588422
Related to: https://github.com/jedrzejboczar/possession.nvim/issues/42

### CODE REVIEW

**Comment by jedrzejboczar** [comment]
Example preview:
Screenshot from 2023-10-27 00-18-14

**Comment by jedrzejboczar** [comment]
We could add some config to the telescope picker to control what is shown in the preview

**Comment by piotr-marendowski** [comment]
My look:
image
Looking great! This gray highlight is very pleasing.
image

Would be nice to show the `Plugin data` only if it has something (breakpoints etc.) and not by default. Also I have really short previewer (not only for this plugin - some time ago I played around with telescope config), so an option to wrap basically everything would be helpful. Also an [option to disable previewer](https://github.com/jedrzejboczar/possession.nvim/pull/43#discussion_r1369815714) with configuration options would be useful.

> We could add some config to the telescope picker to control what is shown in the preview

So we would add e.g. `show_cwd` (and others) or something like this?

**Comment by jedrzejboczar** [comment]
Good idea, I'll try to avoid plugin data when there's nothing interesting. 

> So we would add e.g. show_cwd (and others) or something like this?

Yes, something like this. Probably just something like `{ name = true, file = true, cwd = false, ... }`.

I didn't have much time recently, but maybe I'll find some time this week to finish this.

**Comment by piotr-marendowski** [comment]
image

I meant wrap paths so that if they are too long to fit in the whole previewer they are cut and portion of them is on the next line.

**Comment by jedrzejboczar** [comment]
Changes:
* removes empty plugin_data
* highlights CWD/TAB_CWD in paths instead of just finding a single common prefix

**Comment by piotr-marendowski** [comment]
image
Looks great! Thanks for it!

**Pull request merged**
